### ISSUE TITLE
使用artisan命令 php artisan module:create Test 创建模块出错

### ISSUE THREAD

**Issue by xieguo** [zotopteam/zotop-plus#11]
Branch: develop
Commit: dfdb103
Description: artisan命令 php artisan module:create Test 创建模块出错。
Laravel log:
[2019-06-04 14:03:44] local.ERROR: The "C:\xampp\htdocs\workspace\test-cms\modules/Core/Console/stubs/views/api-controller/simple" directory does not exist. {"exception":"[object] (Symfony\\Component\\Finder\\Exception\\DirectoryNotFoundException(code: 0): The \"C:\\xampp\\htdocs\\workspace\
test-cms\\modules/Core/Console/stubs/views/api-controller/simple\" directory does not exist. at C:\\xampp\\htdocs\\workspace\
test-cms\\vendor\\symfony\\finder\\Finder.php:601)
[stacktrace]
#0 C:\\xampp\\htdocs\\workspace\
test-cms\\vendor\\laravel\\framework\\src\\Illuminate\\Filesystem\\Filesystem.php(414): Symfony\\Component\\Finder\\Finder->in('C:\\\\xampp\\\\htdocs...')
#1 C:\\xampp\\htdocs\\workspace\
test-cms\\modules\\Core\\Console\\ApiControllerCommand.php(190): Illuminate\\Filesystem\\Filesystem->files('C:\\\\xampp\\\\htdocs...')
#2 C:\\xampp\\htdocs\\workspace\
test-cms\\modules\\Core\\Console\\ApiControllerCommand.php(63): Modules\\Core\\Console\\ApiControllerCommand->getViewFiles()
#3 C:\\xampp\\htdocs\\workspace\
test-cms\\modules\\Core\\Console\\ApiControllerCommand.php(52): Modules\\Core\\Console\\ApiControllerCommand->createViews()
#4 [internal function]: Modules\\Core\\Console\\ApiControllerCommand->handle()
#5 C:\\xampp\\htdocs\\workspace\
test-cms\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(32): call_user_func_array(Array, Array)
#6 C:\\xampp\\htdocs\\workspace\
test-cms\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(90): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#7 C:\\xampp\\htdocs\\workspace\
test-cms\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#8 C:\\xampp\\htdocs\\workspace\
test-cms\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(576): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#9 C:\\xampp\\htdocs\\workspace\
test-cms\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(183): Illuminate\\Container\\Container->call(Array)
#10 C:\\xampp\\htdocs\\workspace\
test-cms\\vendor\\symfony\\console\\Command\\Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Illuminate\\Console\\OutputStyle))
#11 C:\\xampp\\htdocs\\workspace\
test-cms\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Illuminate\\Console\\OutputStyle))
#12 C:\\xampp\\htdocs\\workspace\
test-cms\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(198): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Illuminate\\Console\\OutputStyle))
#13 C:\\xampp\\htdocs\\workspace\
test-cms\\modules\\Core\\Console\\CreateCommand.php(197): Illuminate\\Console\\Command->call('module:make-api...', Array)
#14 C:\\xampp\\htdocs\\workspace\
test-cms\\modules\\Core\\Console\\CreateCommand.php(107): Modules\\Core\\Console\\CreateCommand->createResources()
#15 [internal function]: Modules\\Core\\Console\\CreateCommand->handle()
#16 C:\\xampp\\htdocs\\workspace\
test-cms\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(32): call_user_func_array(Array, Array)
#17 C:\\xampp\\htdocs\\workspace\
test-cms\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(90): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#18 C:\\xampp\\htdocs\\workspace\
test-cms\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#19 C:\\xampp\\htdocs\\workspace\
test-cms\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(576): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#20 C:\\xampp\\htdocs\\workspace\
test-cms\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(183): Illuminate\\Container\\Container->call(Array)
#21 C:\\xampp\\htdocs\\workspace\
test-cms\\vendor\\symfony\\console\\Command\\Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#22 C:\\xampp\\htdocs\\workspace\
test-cms\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#23 C:\\xampp\\htdocs\\workspace\
test-cms\\vendor\\symfony\\console\\Application.php(921): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#24 C:\\xampp\\htdocs\\workspace\
test-cms\\vendor\\symfony\\console\\Application.php(273): Symfony\\Component\\Console\\Application->doRunCommand(Object(Modules\\Core\\Console\\CreateCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#25 C:\\xampp\\htdocs\\workspace\
test-cms\\vendor\\symfony\\console\\Application.php(149): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#26 C:\\xampp\\htdocs\\workspace\
test-cms\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Application.php(90): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#27 C:\\xampp\\htdocs\\workspace\
test-cms\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(133): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#28 C:\\xampp\\htdocs\\workspace\
test-cms\\artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#29 {main}
"}

**Comment by zotopteam** [comment]
C:\xampp\htdocs\workspace\test-cms\modules/Core/Console/stubs/views/api-controller/simple 看你的提示是没有这个目录

**Comment by zotopteam** [comment]
这是一个bug，git提交时，没有提交上这个目录，稍后修正

**Comment by zotopteam** [comment]
已经修正并提交到develop分支

**Comment by zotopteam** [comment]
另外：建议使用模块开发功能来开发新模块，可视化ui，操作更简单，命令行里面有太多命令了，使用起来并不方便，开启：模块开发，需要安装开发助手模块并在系统设置-系统安全中切换到local本地环境

**Comment by xieguo** [comment]
> 另外：建议使用【主页】-【模块开发】功能来开发新模块，可视化ui，操作更简单，命令行里面有太多命令了，而且每个命令参数都不太一样，使用起来并不方便，如果没有【模块开发】，需要安装开发助手模块并在系统设置-系统安全中切换到local本地环境

非常感谢，今天又get了。谢谢。
