### ISSUE TITLE
添加文章，选择已有分类

### ISSUE THREAD

**Issue by xieguo** [zotopteam/zotop-plus#12]
首先，这不是一个issue,有这样一个场景：
Step 1: 在后台 **内容管理** 中，添加一个顶级分类叫 **文章分类**。
Step 2: 在 **文章分类** 下增加子类 **原创文章** 和 **网络文章** 分类。
Step 3: 现在增加一个文章，要求在添加文章内容中，可以选择 Step 1和 Step 2所创建的分类。

想问一下，这该如何操作或实现？谢谢。

**Comment by zotopteam** [comment]
> Step 3: 现在增加一个文章，要求在添加文章内容中，可以选择 Step 1和 Step 2所创建的分类。


这是什么意思？

**Comment by xieguo** [comment]
> > Step 3: 现在增加一个文章，要求在添加文章内容中，可以选择 Step 1和 Step 2所创建的分类。
> 
> 这是什么意思？

简单点说，比方我添加一篇文章(也不一定是文章)，但在添加具体内容的时候，需要为将要添加的文章指定一个分类。这个分类以下拉列表的形式出现。但下拉列表(A)里的option值数据，是来自另一张表中的数据。我该如何在添加文章的时候，把另一张表的数据拿出来，放到下拉列表(A)中？

**Comment by xieguo** [comment]
> > Step 3: 现在增加一个文章，要求在添加文章内容中，可以选择 Step 1和 Step 2所创建的分类。
> 
> 这是什么意思？

在添加内容的时候，很多情况，都会指定内容是属于哪一个分类，或来源。如果分类或来源是放到另一张表做统一管理，那么在zotop-plus cms中，如何把这样的表数据在UI上呈现出来，让操作人员做一个选择？我知道zotop-plus cms中有一个多选的表单控件，只要选择多选，就可以填写一个或多个option.但如果不填写，而只是选择另一张表的的数据，作为下拉列表option的值。该如何做？或者说zotop-plus cms是如何实现类似的功能的呢？

**Comment by zotopteam** [comment]
你可能理解错了zotop的内容管理方式，zotop是按照文件夹模式无限分类下去，每个文章在添加的时候，就已经添加到了某个分类中，不能额外指定分类，额外组织内容的方式是tag标签，这个暂时还没有这个功能

**Comment by zotopteam** [comment]
一个典型的分类组织方式：比如新闻中心，你在根目录添加一个新闻中心分类，然后可以直接在新闻中心下添加文章，也可以在新闻中心下添加  公司新闻，行业新闻这种二级分类，属于公司新闻的文章添加在 公司新闻 这个分类下

**Comment by xieguo** [comment]
> 你可能理解错了zotop的内容管理方式，zotop是按照文件夹模式无限分类下去，每个文章在添加的时候，就已经添加到了某个分类中，不能额外指定分类，额外组织内容的方式是tag标签，这个暂时还没有这个功能

应该是的。我觉得我应该理解错了。但我觉得奇怪的是，一篇文章属于某一个特定的分类，是没有问题的，是可以理解的。但文章的某一个属性，比如 文章来源，是可以不同的。它可能来源于a或b,或者c.我把a,b,c放到另一张表 文章来源表 D 里，一个来源一条记录，并把表加入主键。这样我只需要在添加文章的时候，记录 文章来源表D 的记录主键即可。最终，我就可以关联查询相关的表，把需要的内容select出来了。

**Comment by zotopteam** [comment]
> > 你可能理解错了zotop的内容管理方式，zotop是按照文件夹模式无限分类下去，每个文章在添加的时候，就已经添加到了某个分类中，不能额外指定分类，额外组织内容的方式是tag标签，这个暂时还没有这个功能
> 
> 应该是的。我觉得我应该理解错了。但我觉得奇怪的是，一篇文章属于某一个特定的分类，是没有问题的，是可以理解的。但文章的某一个属性，比如 文章来源，是可以不同的。它可能来源于a或b,或者c.我把a,b,c放到另一张表 文章来源表 D 里，一个来源一条记录，并把表加入主键。这样我只需要在添加文章的时候，记录 文章来源表D 的记录主键即可。最终，我就可以关联查询相关的表，把需要的内容select出来了。

不需要那么麻烦的，但是可能这种方式目前是缺少按照来源展示内容的方法，比如选择出来全部来自 某个网站的转载文章，如果有这种需要，那应该是定义一个来源字段，在文章编辑中使用这个来源自动 数据从单独的来源表中读取，这样就可以组织了，但是一般也没这种需要

**Comment by xieguo** [comment]
> 一个典型的分类组织方式：比如新闻中心（编号1，别名slug是news-center），你在根目录添加一个新闻中心分类，然后可以直接在新闻中心下添加文章，也可以在新闻中心下添加 公司新闻（编号2），行业新闻（编号3）这种二级分类，属于公司新闻的文章添加在 公司新闻 这个分类下
> 
> 模板中使用zotop中已经定义的 content:list 标签来展示列表，你可以使用下面方式来调取新闻中心的数据
> 
> {content:list id="1" subdir="true" with="user" model="article" size="4"}
> 
> 或者
> 
> {content:list slug="news-center" subdir="true" with="user" model="article" size="4"}
> 
> 你也可以单独使用下面方式展示公司新闻或者行业新闻数据
> {content:list id="2" }
> {content:list id="3" model="article" size="10"}
> 
> 必须有id或者slug属性，其余属性为可选
> 
> subdir="true" 展示所有下级分类中的数据
> with="user" 关联user模型，可以在列表中显示用户名称
> model="article" 用于限制只获取文章类型的数据
> size="4" 展示4条
> view=“content::tag.image” 可以单独指定展示的模板，不指定调用默认的content::tag.list模板
> 
> \themes\default\views\content\tag 主题目录下定义 list.blade.php 或者 image.blade.php
> 
> 如果content::tag.image模板存在，可以按照content::tag.image模板来展示
> 
> {content:list id="2" view=“content::tag.image” }

非常感谢，这个我能理解。但我觉得一个表的某个字段，关联另一张表的主键。这样的表关联，应该说挺常见的吧。只是我还不太能理解。几乎zotop有更好的实现方式。

**Comment by zotopteam** [comment]
> 非常感谢，这个我能理解。但我觉得一个表的某个字段，关联另一张表的主键。这样的表关联，应该说挺常见的吧。只是我还不太能理解。几乎zotop有更好的实现方式。

在很早以前的zotop版本中是这样处理的，但是那个已经停止更新了，那个不是laravel开发的，是我自己写的框架做的，很多人都觉得自己写的框架二次开发太麻烦，所以后面我用laravel重做了这个plus版本，里面很多设计和早期的zotop并不一样

**Comment by xieguo** [comment]
> > 非常感谢，这个我能理解。但我觉得一个表的某个字段，关联另一张表的主键。这样的表关联，应该说挺常见的吧。只是我还不太能理解。几乎zotop有更好的实现方式。
> 
> 在很早以前的zotop版本中是这样处理的，那个里面分类和内容是分开的两张表设计的，采用的就是你说的这种 关联，这个关联很常见，但是需要自定义分类字段时就麻烦了，所以新版中把分类也看做内容的一部分，而不是内容的一个功能
> 
> 举个例子：目前分类只有名称，如果有一天你的分类需要一个 英文名称，那是不是得去改分类程序，但是作为内容的一部分，内容模型都是可以自定义的，你就只需要在后台修改分类模型即可
> 
> 但是那个已经停止更新了，那个不是laravel开发的，是我自己写的框架做的，很多人都觉得自己写的框架二次开发太麻烦，所以后面我用laravel重做了这个plus版本，里面很多设计和早期的zotop并不一样

非常感谢，您的释惑。我有一些理解了。谢谢你。
