### ISSUE TITLE
compact(): Undefined variable

### ISSUE THREAD

**Issue by sunshidan** [zotopteam/zotop-plus#14]
"compact(): Undefined variable: source" 
在/modules/Translator/start.php 这个文件报这个错
\Form::macro('translate', function($attrs) {
    $value  = $this->getValue($attrs);
    $id     = $this->getId($attrs);
    $name   = $this->getAttribute($attrs, 'name');
    $button = $this->getAttribute($attrs, 'button', trans('translator::translator.button'));
    
    $options = [
        'url'       => $this->getAttribute($attrs, 'url',  route('translator.translate')),
        'source'    => $this->getAttribute($attrs, 'source',  ''),
        'format'    => $this->getAttribute($attrs, 'format', ''),
        'from'      => $this->getAttribute($attrs, 'from', ''),
        'to'        => $this->getAttribute($attrs, 'to', ''),
        'maxlength' => $this->getAttribute($attrs, 'maxlength', '', false),
        'separator' => $this->getAttribute($attrs, 'separator', ''),
    ];

    return $this->toHtmlString(
        $this->view->make('translator::field.translate')->with(compact('name', 'id', 'value', 'attrs', 'source', 'button', 'options'))->render()//这句话报错 提示找不到source变量
    );
});

解决方法定义一个$source='';变量即可 我的php环境时php7.3.6

**Comment by zotopteam** [comment]
可以请问一下报错的详情嘛，报错的行数是多少？我检查一下是否是兼容问题

**Comment by zotopteam** [comment]
`    $this->view->make('translator::field.translate')->with(compact('name', 'id', 'value', 'attrs', 'source', 'button', 'options'))->render()
`

改为

`        $this->view->make('translator::field.translate')->with(compact('name', 'id', 'value', 'attrs', 'button', 'options'))->render()
`

直接传递source是之前版本的做法，后面版本已经改成了通过options 传递，这里忘记修改了，但是奇怪的是我这里并未报错，感谢反馈，后续版本将修正
