### ISSUE TITLE
表单控件类型

### ISSUE THREAD

**Issue by xieguo** [zotopteam/zotop-plus#7]
分支和版本与issue5一致

这不是一个issue.我就想问一下，表单控件，什么时候能有 关联。即一个input与另一个input 关联。比如在后台 实现 省份、城市 级联菜单 联动。

**Comment by zotopteam** [comment]
表单关联属于前端部分，和控件无关本身无关（当然，如果你需要省市联动，可以开发一个模块定义一个关联控件，参照core start.php里面的控件定义方式）

**Comment by xieguo** [comment]
> 表单关联属于前端部分，和控件无关本身无关（当然，如果你需要省市联动，可以开发一个模块定义一个关联控件，参照core start.php里面的控件定义方式）

非常感谢。不过需要更正一点，测试是基于 develop branch,而非master分支。非常抱歉呀。

**Comment by xieguo** [comment]
> 表单关联属于前端部分，和控件无关本身无关（当然，如果你需要省市联动，可以开发一个模块定义一个关联控件，参照core start.php里面的控件定义方式）

谢谢你的建议。

**Comment by zotopteam** [comment]
windows上测试可以使用laragon这个集成环境，比xampp好用许多
