### ISSUE TITLE
安装Server Error

### ISSUE THREAD

**Issue by xieguo** [zotopteam/zotop-plus#8]
branch：develop
commit: d67e4d1b7225f3b5705a87f93592ee3b5a115e7a 
commit时间:  2019-05-28
描述：用develop分支对 zoto-plus 进行安装，在安装进度到达大概 13%时，出现 **Server Error**;  track message 如下：

备：试着把modules/Content/Database/Migrations/2018_11_13_172346_create_content_field_table_1542101025.php
下，第34，35行的code,由
$table->timestamp('created_at');
$table->timestamp('updated_at');
修改成
$table->timestamp('created_at')**->nullable()**;
$table->timestamp('updated_at')**->nullable()**;
后，再重新安装，安装能够顺利完成。

[2019-05-29 12:24:20] local.ERROR: SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'updated_at' (SQL: create table `plus_content_field` (`id` int unsigned not null auto_increment primary key, `model_id` char(64) not null comment '模型编号', `label` varchar(100) not null comment '显示的标签名称', `type` varchar(100) not null comment '控件类型，如text，number等', `name` varchar(100) null comment '数据库中的字段名称', `default` text null comment '默认值', `settings` text null comment '控件设置，如radio，select等的选项', `help` varchar(255) null comment '控件提示信息', `post` tinyint(1) null default '1' comment '是否允许前台填写提交，0：不允许，1：允许', `search` tinyint(1) null default '0' comment '是否允许搜索，0：禁止，1：允许', `system` tinyint(1) null default '0' comment '是否为系统字段，0：自定义字段，1：系统字段', `position` varchar(64) null default 'main' comment '控件位置，main=主区域 side=侧边区域', `width` varchar(64) null default 'w-100' comment '控件宽度，主区域可用', `sort` int unsigned null default '0' comment '排序字段', `disabled` tinyint(1) null default '0' comment '是否禁用，0：未禁用，1：禁用', `created_at` timestamp not null, `updated_at` timestamp not null) default character set utf8 collate 'utf8_unicode_ci') {"exception":"[object] (Illuminate\\Database\\QueryException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'updated_at' (SQL: create table `plus_content_field` (`id` int unsigned not null auto_increment primary key, `model_id` char(64) not null comment '模型编号', `label` varchar(100) not null comment '显示的标签名称', `type` varchar(100) not null comment '控件类型，如text，number等', `name` varchar(100) null comment '数据库中的字段名称', `default` text null comment '默认值', `settings` text null comment '控件设置，如radio，select等的选项', `help` varchar(255) null comment '控件提示信息', `post` tinyint(1) null default '1' comment '是否允许前台填写提交，0：不允许，1：允许', `search` tinyint(1) null default '0' comment '是否允许搜索，0：禁止，1：允许', `system` tinyint(1) null default '0' comment '是否为系统字段，0：自定义字段，1：系统字段', `position` varchar(64) null default 'main' comment '控件位置，main=主区域 side=侧边区域', `width` varchar(64) null default 'w-100' comment '控件宽度，主区域可用', `sort` int unsigned null default '0' comment '排序字段', `disabled` tinyint(1) null default '0' comment '是否禁用，0：未禁用，1：禁用', `created_at` timestamp not null, `updated_at` timestamp not null) default character set utf8 collate 'utf8_unicode_ci') at C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php:664, Doctrine\\DBAL\\Driver\\PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'updated_at' at C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:119, PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'updated_at' at C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:117)
[stacktrace]
#0 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('create table `p...', Array, Object(Closure))
#1 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(459): Illuminate\\Database\\Connection->run('create table `p...', Array, Object(Closure))
#2 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Schema\\Blueprint.php(97): Illuminate\\Database\\Connection->statement('create table `p...')
#3 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Schema\\Builder.php(278): Illuminate\\Database\\Schema\\Blueprint->build(Object(Illuminate\\Database\\MySqlConnection), Object(Illuminate\\Database\\Schema\\Grammars\\MySqlGrammar))
#4 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Schema\\Builder.php(167): Illuminate\\Database\\Schema\\Builder->build(Object(Illuminate\\Database\\Schema\\Blueprint))
#5 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Facades\\Facade.php(237): Illuminate\\Database\\Schema\\Builder->create('content_field', Object(Closure))
#6 C:\\xampp\\htdocs\\workspace\\hostpital\\modules\\Content\\Database\\Migrations\\2018_11_13_172346_create_content_field_table_1542101025.php(38): Illuminate\\Support\\Facades\\Facade::__callStatic('create', Array)
#7 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Migrations\\Migrator.php(385): CreateContentFieldTable1542101025->up()
#8 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Migrations\\Migrator.php(394): Illuminate\\Database\\Migrations\\Migrator->Illuminate\\Database\\Migrations\\{closure}()
#9 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Migrations\\Migrator.php(197): Illuminate\\Database\\Migrations\\Migrator->runMigration(Object(CreateContentFieldTable1542101025), 'up')
#10 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Migrations\\Migrator.php(164): Illuminate\\Database\\Migrations\\Migrator->runUp('C:\\\\xampp\\\\htdocs...', 3, false)
#11 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Migrations\\Migrator.php(111): Illuminate\\Database\\Migrations\\Migrator->runPending(Array, Array)
#12 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Console\\Migrations\\MigrateCommand.php(71): Illuminate\\Database\\Migrations\\Migrator->run(Array, Array)
#13 [internal function]: Illuminate\\Database\\Console\\Migrations\\MigrateCommand->handle()
#14 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(32): call_user_func_array(Array, Array)
#15 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(90): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#16 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#17 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(576): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#18 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(183): Illuminate\\Container\\Container->call(Array)
#19 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\symfony\\console\\Command\\Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Illuminate\\Console\\OutputStyle))
#20 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Illuminate\\Console\\OutputStyle))
#21 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(198): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Illuminate\\Console\\OutputStyle))
#22 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\
widart\\laravel-modules\\src\\Commands\\MigrateCommand.php(73): Illuminate\\Console\\Command->call('migrate', Array)
#23 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\
widart\\laravel-modules\\src\\Commands\\MigrateCommand.php(46): Nwidart\\Modules\\Commands\\MigrateCommand->migrate(Object(Nwidart\\Modules\\Laravel\\Module))
#24 [internal function]: Nwidart\\Modules\\Commands\\MigrateCommand->handle()
#25 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(32): call_user_func_array(Array, Array)
#26 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(90): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#27 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#28 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(576): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#29 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(183): Illuminate\\Container\\Container->call(Array)
#30 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\symfony\\console\\Command\\Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Illuminate\\Console\\OutputStyle))
#31 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Illuminate\\Console\\OutputStyle))
#32 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\symfony\\console\\Application.php(908): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Symfony\\Component\\Console\\Output\\BufferedOutput))
#33 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\symfony\\console\\Application.php(269): Symfony\\Component\\Console\\Application->doRunCommand(Object(Nwidart\\Modules\\Commands\\MigrateCommand), Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Symfony\\Component\\Console\\Output\\BufferedOutput))
#34 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\symfony\\console\\Application.php(145): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Symfony\\Component\\Console\\Output\\BufferedOutput))
#35 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Application.php(90): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Symfony\\Component\\Console\\Output\\BufferedOutput))
#36 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Application.php(182): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Symfony\\Component\\Console\\Output\\BufferedOutput))
#37 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(275): Illuminate\\Console\\Application->call('module:migrate', Array, NULL)
#38 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Facades\\Facade.php(237): Illuminate\\Foundation\\Console\\Kernel->call('module:migrate', Array)
#39 C:\\xampp\\htdocs\\workspace\\hostpital\\modules\\Core\\start.php(85): Illuminate\\Support\\Facades\\Facade::__callStatic('call', Array)
#40 [internal function]: Nwidart\\Modules\\Laravel\\Module->{closure}(true)
#41 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Traits\\Macroable.php(110): call_user_func_array(Object(Closure), Array)
#42 C:\\xampp\\htdocs\\workspace\\hostpital\\app\\Http\\Controllers\\InstallController.php(380): Nwidart\\Modules\\Module->__call('install', Array)
#43 [internal function]: App\\Http\\Controllers\\InstallController->modules(Object(Illuminate\\Http\\Request))
#44 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Controller.php(54): call_user_func_array(Array, Array)
#45 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('modules', Array)
#46 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\InstallController), 'modules')
#47 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(176): Illuminate\\Routing\\Route->runController()
#48 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(680): Illuminate\\Routing\\Route->run()
#49 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#50 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#51 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#52 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#53 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken.php(75): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#54 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#55 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#56 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#57 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#58 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#59 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php(56): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#60 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#61 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#62 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#63 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#64 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#65 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\EncryptCookies.php(66): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#66 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#67 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#68 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#69 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(682): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#70 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(657): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#71 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(623): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#72 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(612): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#73 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#74 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#75 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\fideloper\\proxy\\src\\TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#76 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#77 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#78 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#79 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#80 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#81 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#82 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#83 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#84 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#85 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#86 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#87 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#88 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#89 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#90 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#91 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#92 C:\\xampp\\htdocs\\workspace\\hostpital\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#93 C:\\xampp\\htdocs\\workspace\\hostpital\\public\\index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#94 {main}
"}

**Comment by zotopteam** [comment]
虽然我这里安装没报错，但是你备注的地方加入nullable是有道理的，已经修改，等待提交

**Comment by zotopteam** [comment]
develop 分支 ：已经优化，field迁移改为你建议中的：
$table->timestamp('created_at')->nullable();
$table->timestamp('updated_at')->nullable();

**Comment by zotopteam** [comment]
这里备注一点，数据表迁移代码是程序自动生成的，较早生成的代码中可能有部分代码没有加入->nullable();我发现后改了生成迁移代码的程序，但是有些较老版本的迁移我并没有覆盖，我一般设计数据表是这样做的：在数据库里面建一个数据表（也可以使用开发助手的中的数据表来建，这样表名一般都是自动加入了cms_前缀和模块前缀，比如 cms_content_model）,然后开发助手程序中自动生成迁移，或者在修改数据表之后，使用覆盖现在迁移功能来生成数据表迁移，省去了手动去写迁移的麻烦
