### ISSUE TITLE
区域和区块

### ISSUE THREAD

**Issue by xieguo** [zotopteam/zotop-plus#9]
首先，这不是一个issue. 仅仅是自己想搞清楚的名词概念和用法。

区域： 区域管理，但何为区域管理呀？用在什么地方呢？是否可以提供一下 user case.

区块：定义管理页上的小部件，这个从字面上，还可以理解，虽然不知道怎么用。

然后：真切的想一下，zoto-plus project的该文档，准备啥时候更新呢？

最后，非常感谢。谢谢。

**Comment by zotopteam** [comment]
区域：你可以理解为省市县这种，暂时只提供了模块功能，并没有提供任何数据
区块：就是页面上的小部件，一般有以下几种用法：
1，有个单独的公司简介需要展示，可以在后台建一个别名为about的图文区块，然后使用{block slug="about"} 放在模板里面，即可在页面上展示
2，你有个统计代码需要放在前端，可以在后台建一个别名为code的代码区块，然后使用{block slug="code"} 放在模板里面，即可在页面上展示
3，有一个轮播图，你可以建一个别名为slide列表区块，字段选择为标题、链接和图片，这样你添加列表后，就可用{block slug="slide"} 在前台显示轮播图，当然需要配合对应的模板才可以，模板可以在后台设置，也可以前台 {block slug="slide" view="xxxxx"} 这样使用，没有view属性时，使用后台区块设置的模板

**Comment by xieguo** [comment]
> **区域：你可以理解为省市县这种，暂时只提供了模块功能，并没有提供任何数据**
> **区块：就是页面上的小部件，一般有以下几种用法：**
> 1，有个单独的公司简介需要展示，可以在后台建一个别名为about的图文区块，然后使用{block slug="about"} 放在模板里面，即可在页面上展示
> 2，你有个统计代码需要放在前端，可以在后台建一个别名为code的代码区块，然后使用{block slug="code"} 放在模板里面，即可在页面上展示
> 3，有一个轮播图，你可以建一个别名为slide列表区块，字段选择为标题、链接和图片，这样你添加列表后，就可用{block slug="slide"} 在前台显示轮播图，当然需要配合对应的模板才可以，模板可以在后台设置，也可以前台 {block slug="slide" view="xxxxx"} 这样使用，没有view属性时，使用后台区块设置的模板
> 
> 区块是一个很强的功能，网站上的零散数据都可以使用这个来定义，后期会从内容推送数据到区块的功能，这样可以更灵活的展示内容

非常

> **区域：你可以理解为省市县这种，暂时只提供了模块功能，并没有提供任何数据**
> **区块：就是页面上的小部件，一般有以下几种用法：**
> 1，有个单独的公司简介需要展示，可以在后台建一个别名为about的图文区块，然后使用{block slug="about"} 放在模板里面，即可在页面上展示
> 2，你有个统计代码需要放在前端，可以在后台建一个别名为code的代码区块，然后使用{block slug="code"} 放在模板里面，即可在页面上展示
> 3，有一个轮播图，你可以建一个别名为slide列表区块，字段选择为标题、链接和图片，这样你添加列表后，就可用{block slug="slide"} 在前台显示轮播图，当然需要配合对应的模板才可以，模板可以在后台设置，也可以前台 {block slug="slide" view="xxxxx"} 这样使用，没有view属性时，使用后台区块设置的模板
> 
> 区块是一个很强的功能，网站上的零散数据都可以使用这个来定义，后期会从内容推送数据到区块的功能，这样可以更灵活的展示内容

非常感谢你的热心答复。

**Comment by zotopteam** [comment]
：），非常感谢你的耐心测试和反馈，zotop的路还很长，需要更多测试和开发，后期会越来越完善
